### ISSUE TITLE
Missing release with Python 3 support

### ISSUE THREAD

**Issue by fwerner** [jimbraun/XCDF#107]
There has been no release since the addition of Python 3 support. @jimbraun, if there are no known issues with the current state of the codebase, could you please consider making a release? It would greatly simplify packaging XCDF.

**Comment by jimbraun** [comment]
I have no problem with a new release.  Pinging @HealthyPear who has an open PR.

**Comment by HealthyPear** [comment]
You have my blessing 😄

**Comment by jimbraun** [comment]
Unless I hear otherwise, I'll release version 3.1 tomorrow.

**Comment by fwerner** [comment]
A kind reminder for the above - if there isn't any other showstopper. 🤗

**Comment by jimbraun** [comment]
Release is done.
