### ISSUE TITLE
Add histogramming capability

### ISSUE THREAD

**Issue by jimbraun** [jimbraun/XCDF#13]
From Trac:

Segev:

The XCDF library currently has a Histogram python module that can be used to create 1D histograms without loading XCDF data into memory (in contrast with numpy.histogram). People are starting to use it because our data are no longer being written in ROOT format. However, the python Histogram is slow and does not take advantage of the fast variable selection made possible using the field visitor pattern in XCDF.
So, a couple of questions for users:
Should we add a C++ histogram class to XCDF (+ python bindings) with selection routines similar to those in xcdf-utility?
Should this class be added directly to the XCDF library or as a project in AERIE that builds off XCDF?
The advantage of adding the class directly to XCDF is that we can do analysis on REC data without actually needing to load the AERIE environment. The disadvantage is that XCDF could become bloated over time if we start packing it with analysis features. Any thoughts?

Lukas:

A 3rd possibility could be a new xcdf-utility collection, that builds on xcdf, but won't require the whole aerie framework. This way, we avoid xcdf bloat for uses that only need an efficient storage library. This could also help to avoid contaminating the base xcdf code with non-core functions. The price to pay is yet another package, but ape could provide an xcdf-anslysis package to help installing xcdf+histogram only.

Jim:

I intended to implement this functionality in XCDF. I'll move this ticket to the XCDF repository:
 https://github.com/jimbraun/XCDF/issues

**Comment by HealthyPear** [comment]
I think you can close this issue, as with the new Python3 bindings any other operation can be done basically using just numpy after loading the data.
