### ISSUE TITLE
Unable to grab fields by name at a given record

### ISSUE THREAD

**Issue by jimbraun** [jimbraun/XCDF#56]
getRecord() calls Rewind() after the data is returned, making it impossible to extract data for a given field at a given record without iterating through the entire file.

**Comment by sybenzvi** [comment]
We can investigate the possibility of adding kwargs to the getRecord interface so that calls like this are possible:

xf.getRecord(n, fields="x, y, z")

It may take a little bit of tweaking of the XCDF visitor classes.
