### ISSUE TITLE
XCDF-Utility recovers no events 

### ISSUE THREAD

**Issue by Lilcupcake** [jimbraun/XCDF#58]
xcdf-utility recover was not recovering any events this issue appear somewhere between 2.07 and 2.09. 

Here is in an example of the difference between the two versions: 

./xcdf-utility version
XCDF version 2.9.0
xcdf-utility recover -o test.xcd $HAWCROOT/data/hawc/data/2014/12/run002186/trig_run002186_00002.xcd
XCDF FATAL ERROR: /tmp/xcdf/xcdf-2.09.00/src/XCDFFile.cc,ReadFrame:375]: Read failed.  Byte offset: 86745736
Corrupt file: Recovered 0 events.

 ./xcdf-utility version
XCDF version 2.7.0
./xcdf-utility recover -o test2.xcd $HAWCROOT/data/hawc/data/2014/12/run002186/trig_run002186_00002.xcd
XCDF FATAL ERROR: /data/disk01/home/iwisher/XCDF_old/XCDF-2.07.00/src/XCDFFile.cc,ReadFrame:370]: Read failed.  Byte offset: 86745736
Corrupt file: Recovered 142490 events.

**Comment by jimbraun** [comment]
Fixed:

[master 71b0b4f] Fix recover.  Don't try to copy comments until we have to
 2 files changed, 9 insertions(+), 7 deletions(-)

[master fbb6aec] Fix recover for normal files specified on the command line.  Before, recovery only worked for files with no block table or files read on std::cin
 3 files changed, 10 insertions(+), 2 deletions(-)
