### ISSUE TITLE
Eliminate concatenation

### ISSUE THREAD

**Issue by jimbraun** [jimbraun/XCDF#67]
We never used it, and it needlessly complicates the code.

**Comment by jrpretz** [comment]
You mean the fact that you can concatenate xcdf files and get a valid xcdf file? I use it regularly. I use it when finding a bunch of isolated gamma rays. I then cat each separate file together to get one big file.

**Comment by jimbraun** [comment]
OK, glad to hear...  We'll keep the feature around then.
