### ISSUE TITLE
XCDFFrameType NONE 

### ISSUE THREAD

**Issue by harmscho** [jimbraun/XCDF#83]
In XCDFDefs.h : this enum causes a conflict with an enum in GEANT4 that has the same name.. 
Is it possible to move the enum into a namespace or make it more explicit XCDF_NONE?

**Comment by jimbraun** [comment]
I've committed the change, that's no problem.  You'll of course need a new ape release to use it.  It may be easier to factor the XCDF code into a separate .cc file.
