### ISSUE TITLE
Add a new field in python

### ISSUE THREAD

**Issue by jasonfan1997** [jimbraun/XCDF#85]
Hi, I want to add a new field to the xcdf file but I can't get it working.  The thing that I want to do is something xf.addField("rec.proba", float,1), then I have a numpy array that I want to add in the file. Can you show me the correct way to do it?

**Comment by jasonfan1997** [comment]
Never mind. I just saw the old issue.

**Comment by parthasarathipal** [comment]
> Never mind. I just saw the old issue.

where is the solution to this issue? I can not find this.
